### ISSUE TITLE
Set custom codepoint

### ISSUE THREAD

**Issue by pivanov** [nfroidure/gulp-svgicons2svgfont#12]
Hey guys,
nice plugin :) 

Is there an option to set custom codepoint.
In my case I have 4 icons. and the codepoints are:
icon-1.svg 0xE001
icon-2.svg 0xE002
icon-3.svg 0xE003
icon-close.svg 0xE004

I want to set code for the `icon-close.svg`.  if my svg file name is for example `icon-close.svg` I want to set codepoint 0xE600 for example?

Sorry if my question is stupid and Thanks in advance

**Comment by luin** [comment]
A related question that can I customise the codepoint for each font? Say I'd like the four fonts' codepoint are as following:

```
icon-1.svg 0xE001
icon-2.svg 0xE012
icon-3.svg 0xE005
icon-close.svg 0xE007
```

Seems like `appendCodepoints` only works if my codepoint are progressive.

grunt-webfont has a `codepoints` option doing the similar thing: https://github.com/sapegin/grunt-webfont#codepoints

**Comment by nfroidure** [comment]
If you wish to set custom codepoints, just rename the files by prefixing per the codepoint you want.

You can also implement your own logic by overriding the options.metadataProvider value but i just figured out it is undocumented https://github.com/nfroidure/gulp-svgicons2svgfont/blob/master/src/index.js#L47
