### ISSUE TITLE
Error in plugin 'gulp-spawn'

### ISSUE THREAD

**Issue by hellier** [nfroidure/gulp-svgicons2svgfont#16]
I'm using your exact setup for font hinting, and it's returning:

	hellier@anon:~/localhost/foo$ gulp Iconfont
	[22:53:06] Using gulpfile ~/localhost/foo/gulpfile.js
	[22:53:06] Starting 'Iconfont'...
	[22:53:06] Finished 'Iconfont' after 11 ms
	[ { name: 'arrow', codepoint: 'e001' },
		{ name: 'history', codepoint: 'e002' },
		{ name: 'cancel', codepoint: 'e003' },
		{ name: 'cog', codepoint: 'e004' },
		{ name: 'flag', codepoint: 'e005' },
		{ name: 'forum', codepoint: 'e006' },
		{ name: 'logo', codepoint: 'e008' },
		{ name: 'logout', codepoint: 'e00a' },
		{ name: 'tick', codepoint: 'e00b' },
		{ name: 'analysis-', codepoint: 'e00c' },
		{ name: 'note', codepoint: 'e00d' },
		{ name: 'exercise', codepoint: 'e00e' },
		{ name: 'biometric', codepoint: 'e00f' },
		{ name: 'search', codepoint: 'e010' },
		{ name: 'track', codepoint: 'e011' },
		{ name: 'comment', codepoint: 'e012' },
		{ name: 'food', codepoint: 'e013' },
		{ name: 'photo1', codepoint: 'e014' },
		{ name: 'star', codepoint: 'e015' },
		{ name: 'photo', codepoint: 'e016' },
		{ name: 'photos', codepoint: 'e017' },
		{ name: 'workout', codepoint: 'e018' } ] { fontName: 'icon',
		normalize: true,
		appendCodepoints: true,
		descent: 1,
		ignoreExt: false,
		log: [Function],
		error: [Function],
		fixedWidth: false,
		round: 10000000000000 }
	[22:53:07] gulp-svgicons2svgfont: Font created

	events.js:72
					throw er; // Unhandled 'error' event
								^
	Error in plugin 'gulp-spawn'
	No glyph for the key character to derive standard width and height.
	For the latin script, this key character is `o' (U+006F).

			at Socket.<anonymous> (/home/hellier/localhost/foo/node_modules/gulp-spawn/index.js:53:26)
			at Socket.EventEmitter.emit (events.js:117:20)
			at _stream_readable.js:920:16
			at process._tickCallback (node.js:415:13)

**Comment by nfroidure** [comment]
It looks like ttfautohint wants you to define a glyph for the 'o' character. You could add it to your source SVG or find a way to avoid ttfautohint to recognise your font as a latin one. Not a svgicons2svgfont issue though.
