### ISSUE TITLE
May be customize function to generate codepoint throw options

### ISSUE THREAD

**Issue by evilebottnawi** [nfroidure/gulp-svgicons2svgfont#19]
Example:
```javascript
var indexString = 0;
var filename = path.basename(glyph.file, '.svg');
do {
    glyph.codepoint += filename[indexString].charCodeAt();//curCodepoint++;
    indexString++;
} while(-1 !== usedCodePoints.indexOf(glyph.codepoint));
usedCodePoints.push(glyph.codepoint);
console.log(glyph.codepoint);
```

I created function based on filename start with startCodepoint(to avoid displacement)

**Comment by nfroidure** [comment]
Not sure to understand. If you mean allowing to provide some logic to generate glyph names, i would accept a PR with tests and documentation for it.

**Comment by evilebottnawi** [comment]
@nfroidure yes, ok anytime soon

**Comment by nfroidure** [comment]
Since the 2.0.0 version will use this https://github.com/nfroidure/svgicons2svgfont/blob/master/src/metadata.js

You probably could allow to override the metadata service by a custom one in order to create custom logic.

**Comment by evilebottnawi** [comment]
@nfroidure thanks, it is cool and good
