### ISSUE TITLE
startUnicode option overridden by prepended unicode

### ISSUE THREAD

**Issue by pindab0ter** [nfroidure/gulp-svgicons2svgfont#33]
When I set the `startUnicode: 0xEA02`, the first generated glyph still shows `unicode="&#xEA01;"`.

This is the gulp task I've set up:

```js
var gulp = require('gulp'),
    svgicons2svgfont = require('gulp-svgicons2svgfont');

module.exports = {
    task: function() {
        return gulp.src(['img/icons/**/*'])
            .pipe(svgicons2svgfont({
                fontName: 'my-icons',
                appendUnicode: true,
                startUnicode: 0xEA02
            }))
            .on('glyphs', function(glyphs, options) {
                console.log(glyphs, options);
            })
            .pipe(gulp.dest('fonts/'));
    }
};
```

**Comment by pindab0ter** [comment]
The problem was me using the `appendUnicode` setting which prepended (maybe change the name of the option?) the unicode to the filenames. The `startUnicode` setting is overridden by these prepended unicodes, making the setting useless after the first run.

**Comment by nfroidure** [comment]
I agree on the fact it should be prependUnicode, we could change this on the next major version.

Would an "ignoreUnicodePrefixes" option fit your use case?

**Comment by pindab0ter** [comment]
I ended up not needing the feature, but it seems to me that the `startUnicode` overriding the file names should be default behaviour. I'll leave that decision up to you though, since I don't need it for my work flow.
