### ISSUE TITLE
Problem in version 3.0.2

### ISSUE THREAD

**Issue by guysegev** [nfroidure/gulp-svgicons2svgfont#35]
Hi,

We use gulp-iconfont that require gulp-svgicons2svgfont.
Starting today, gulp build fails with the following error:

/node_modules/gulp-svgicons2svgfont/src/index.js:38
gutil.log(...['gulp-svgicons2svgfont:'].concat(
              ^^^

It fails because of these 3 dots.

When I added to packages.json (in order to use your previous version):
"gulp-svgicons2svgfont": "3.0.1"
Everything worked again.

Thanks,
Guy.

**Comment by nfroidure** [comment]
Hi @guysegev 

I bumped the node support to the last LTS. Please revert or upgrade your Node version.

For ref: https://github.com/nfroidure/gulp-svgicons2svgfont/commit/b81e83e905272637ddd6670d01bf7128b60c6d3d
