### ISSUE TITLE
Checkin 4c22ff5 - Update dependencies 

### ISSUE THREAD

**Issue by grahamharris1975** [nfroidure/gulp-svgicons2svgfont#37]
My company uses this to build our product and the build scripts pull the latest versions of gulp from git. The following change in src\index.js has broken our build scripts :

```
-   gutil.log.apply(gutil, ['gulp-svgicons2svgfont:'].concat(
+   gutil.log(...['gulp-svgicons2svgfont:'].concat(
```

**Comment by bastoune** [comment]
+1

**Comment by nfroidure** [comment]
Duplicate of https://github.com/nfroidure/gulp-svgicons2svgfont/issues/38
