### ISSUE TITLE
SyntaxError: 'gulp-svgicons2svgfont' does not provide an export named 'default'

### ISSUE THREAD

**Issue by timint** [nfroidure/gulp-svgicons2svgfont#60]
A syntax error is given with the usage example:
```
import svgicons2svgfont from 'gulp-svgicons2svgfont';
```
SyntaxError: The requested module 'gulp-svgicons2svgfont' does not provide an export named 'default'

**Comment by nfroidure** [comment]
Indeed, my mistake, will fix it asap, using `import { svgicons2svgfont } from 'gulp-svgicons2svgfont';` should work in the meanwhile.
